### PR TITLE
Matcher API & Tests

### PR DESCRIPTION
**Pull request by aliraza0337**
This PR implements the python API that takes a list of criteria and ironic configurations and returns True or False depending on if the criteria is met by the ironic configurations.
It also includes the tests for the matcher code.

### CODE REVIEW

**Comment by tzumainn** [comment]
It may be worth updating the commit message?

**Comment by larsks** [comment]
@tzumainn I thought the description was pretty good. I guess maybe the subject line could use a minor update.

**Comment by tzumainn** [comment]
Yeah, the subject is what I meant.

**Comment by larsks** [comment]
@aliraza0337 did you see Mainn's comment?

**Comment by aliraza0337** [comment]
Yes, let me update.

**Comment by tzumainn** [comment]
Looks good, nice job!

**Pull request merged**
